<?php

namespace JP\AdminBundle\Repository;

/**
 * AvantageSalaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvantageSalaryRepository extends \Doctrine\ORM\EntityRepository
{
}
