<?php

namespace JP\AdminBundle\Repository;

/**
 * EmploiSalaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploiSalaryRepository extends \Doctrine\ORM\EntityRepository
{
}
