<?php

namespace JP\AdminBundle\Repository;

/**
 * ModePaieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModePaieRepository extends \Doctrine\ORM\EntityRepository
{
}
