<?php

namespace JP\AdminBundle\Repository;

/**
 * PositionSalaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionSalaryRepository extends \Doctrine\ORM\EntityRepository
{
}
