<?php

namespace JP\AdminBundle\Repository;

/**
 * PrimeSalaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrimeSalaryRepository extends \Doctrine\ORM\EntityRepository
{
}
