<?php

namespace JP\AdminBundle\Repository;

/**
 * StatusSalaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusSalaryRepository extends \Doctrine\ORM\EntityRepository
{
}
