admin_avantage_index:
    path:     /
    defaults: { _controller: "JPAdminBundle:AvantageSalary:index" }
    methods:  GET

admin_avantage_show:
    path:     /{id}/show
    defaults: { _controller: "JPAdminBundle:AvantageSalary:show" }
    methods:  GET

admin_avantage_new:
    path:     /new
    defaults: { _controller: "JPAdminBundle:AvantageSalary:new" }
    methods:  [GET, POST]

admin_avantage_edit:
    path:     /{id}/edit
    defaults: { _controller: "JPAdminBundle:AvantageSalary:edit" }
    methods:  [GET, POST]

admin_avantage_delete:
    path:     /{id}/delete
    defaults: { _controller: "JPAdminBundle:AvantageSalary:delete" }
    methods:  DELETE
