admin_modepaie_index:
    path:     /
    defaults: { _controller: "JPAdminBundle:ModePaie:index" }
    methods:  GET

admin_modepaie_show:
    path:     /{id}/show
    defaults: { _controller: "JPAdminBundle:ModePaie:show" }
    methods:  GET

admin_modepaie_new:
    path:     /new
    defaults: { _controller: "JPAdminBundle:ModePaie:new" }
    methods:  [GET, POST]

admin_modepaie_edit:
    path:     /{id}/edit
    defaults: { _controller: "JPAdminBundle:ModePaie:edit" }
    methods:  [GET, POST]

admin_modepaie_delete:
    path:     /{id}/delete
    defaults: { _controller: "JPAdminBundle:ModePaie:delete" }
    methods:  DELETE
