admin_offre_index:
    path:     /
    defaults: { _controller: "JPAdminBundle:Offre:index" }
    methods:  GET

admin_offre_show:
    path:     /{id}/show
    defaults: { _controller: "JPAdminBundle:Offre:show" }
    methods:  GET

admin_offre_new:
    path:     /new
    defaults: { _controller: "JPAdminBundle:Offre:new" }
    methods:  [GET, POST]

admin_offre_edit:
    path:     /{id}/edit
    defaults: { _controller: "JPAdminBundle:Offre:edit" }
    methods:  [GET, POST]

admin_offre_delete:
    path:     /{id}/delete
    defaults: { _controller: "JPAdminBundle:Offre:delete" }
    methods:  DELETE
