admin_status_index:
    path:     /
    defaults: { _controller: "JPAdminBundle:StatusSalary:index" }
    methods:  GET

admin_status_show:
    path:     /{id}/show
    defaults: { _controller: "JPAdminBundle:StatusSalary:show" }
    methods:  GET

admin_status_new:
    path:     /new
    defaults: { _controller: "JPAdminBundle:StatusSalary:new" }
    methods:  [GET, POST]

admin_status_edit:
    path:     /{id}/edit
    defaults: { _controller: "JPAdminBundle:StatusSalary:edit" }
    methods:  [GET, POST]

admin_status_delete:
    path:     /{id}/delete
    defaults: { _controller: "JPAdminBundle:StatusSalary:delete" }
    methods:  DELETE
