<?php

namespace JPFichePaieBundle\Repository;

/**
 * CompagnyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichepaieRepository extends \Doctrine\ORM\EntityRepository
{
}
