<?php

namespace JPFichePaieBundle\Repository;

/**
 * PaieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaieRepository extends \Doctrine\ORM\EntityRepository
{
}
